### PR TITLE
Fix login and websocket to work with Airconnect+

### PR DESCRIPTION
**Pull request by rhayun**
its tested and working but i need someone to review this

### CODE REVIEW

**Comment by hllhll** [comment]
Hi, Awesome Thanks a-lot!

1. Does it _Break_ the compatibility with Tadiran connect?
2. The captcha they've implemented is so awkward, that's how not any site should do captcha. It would probebly change when they figure it out that they did a crappy job....
3. I Don't think that's a good idea to disable encryption by default, it's better as a configuration

**Comment by rhayun** [comment]
1. as i know Tadiran connect is no longer working
2. the captcha is not a real captcha - they only match the hidden field with a input text field - its dumb but its works
3. i agree, feel free to do that - better way is to handle the ssl thing

**Comment by yairabf** [comment]
I tried the new code on my HA, keep getting these errors,

1. 
```
 self._ws = websocket.WebSocketApp(wssaddr,sslopt={"cert_reqs": ssl.CERT_NONE}, header=headers, cookie="; ".join(["%s=%s" %(i, j) for i, j in cookies.items()]),
NameError: name 'ssl' is not defined
```

so I added the import SSL, but then I got this error:
2.

`self._ws = websocket.WebSocketApp(wssaddr,sslopt={"cert_reqs": ssl.CERT_NONE}, header=headers, cookie="; ".join(["%s=%s" %(i, j) for i, j in cookies.items()]),
TypeError: __init__() got an unexpected keyword argument 'sslopt'`

**Comment by HawkUser** [comment]
> I tried the new code on my HA, keep getting these errors,
> 
> 
> ```
>  self._ws = websocket.WebSocketApp(wssaddr,sslopt={"cert_reqs": ssl.CERT_NONE}, header=headers, cookie="; ".join(["%s=%s" %(i, j) for i, j in cookies.items()]),
> NameError: name 'ssl' is not defined
> ```
> 
> so I added the import SSL, but then I got this error:
> 2.
> 
> ```
> `self._ws = websocket.WebSocketApp(wssaddr,sslopt={"cert_reqs": ssl.CERT_NONE}, header=headers, cookie="; ".join(["%s=%s" %(i, j) for i, j in cookies.items()]),
> TypeError: __init__() got an unexpected keyword argument 'sslopt'`
> ```

are you running HassOS?

**Comment by yairabf** [comment]
yes

**Comment by HawkUser** [comment]
> yes

I doubled check again with fresh new HassOS no problems exist, can you double-check perhaps there is updates for HassOS you didn't commit?

**Comment by yairabf** [comment]
here is my system:
 

```
arch | armv7l
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.3
supervisor | 240
timezone | Asia/Jerusalem
version | 0.114.4
virtualenv | false

```

still getting those error

**Comment by yairabf** [comment]
ok, after another restart, It worked!

**Pull request merged**
